[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://unpkg.com https://cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline' https://unpkg.com https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data:;
      connect-src 'self' https://portofolio1981.netlify.app;
    """
